
import { GoogleGenAI, Type, Modality } from "@google/genai";

// Assume API_KEY is set in the environment
const API_KEY = process.env.API_KEY;
if (!API_KEY) {
    throw new Error("API_KEY environment variable not set");
}
const ai = new GoogleGenAI({ apiKey: API_KEY });

export const analyzeImage = async (base64Image: string, mimeType: string) => {
    const prompt = `Analyze the provided image. Does it contain one or more clear, high-quality human faces? The faces should be a main subject. Respond ONLY with a JSON object with the following structure: {"isValid": boolean, "reason": string}. If valid, the reason should be 'Valid portrait detected'. If not, provide a brief reason like 'No human faces detected', 'Image is too blurry', or 'Faces are too small in the frame'.`;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: {
            parts: [
                { inlineData: { data: base64Image, mimeType: mimeType } },
                { text: prompt }
            ]
        },
        config: {
            responseMimeType: 'application/json',
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    isValid: { type: Type.BOOLEAN },
                    reason: { type: Type.STRING }
                },
                required: ['isValid', 'reason']
            }
        }
    });

    const jsonText = response.text.trim();
    try {
        return JSON.parse(jsonText);
    } catch (e) {
        console.error("Failed to parse JSON from Gemini:", jsonText);
        throw new Error("Invalid response from image analysis API.");
    }
};


export const transformImage = async (base64Image: string, mimeType: string, country: string): Promise<string> => {
    const prompt = `You are an expert digital artist specializing in cultural transformations. Take the provided user portrait and reimagine the person or people as locals from ${country}.

Task: Edit the image to give the subjects a complete cultural makeover.
- Clothing: Dress them in beautiful, authentic, and traditional ${country} attire.
- Hairstyle: Style their hair in a way that is characteristic of ${country}'s culture.
- Background: Replace the background with a stunning and iconic scene from ${country}, such as a famous landmark or a breathtaking natural landscape.
- Crucial Constraint: DO NOT alter the facial features, identity, or skin tone of the people in the photo. Their faces must remain clearly identifiable as the people in the original photo.
- Output: The final image should be a high-quality, photorealistic composition. Do not add any text or watermarks to the image.`;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image-preview',
        contents: {
            parts: [
                { inlineData: { data: base64Image, mimeType: mimeType } },
                { text: prompt }
            ]
        },
        config: {
            responseModalities: [Modality.IMAGE, Modality.TEXT],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }

    throw new Error("No image was generated by the API.");
};